name: DefaultWorkflow CI

on:
  push:
    branches:
      - 'feat/*'
      - 'feat/**'
      - 'refact/*'
      - 'refact/**'
      - 'develop'
      - 'fix/*'
      - 'fix/**'
      - 'fix/**'
      - '*'
      - '!master'
      - '!release*'

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ktlint
        run: bash ./gradlew ktlint --stacktrace

  unit-tests:
    name: Run tests
    needs: [ktlint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  android_tests:
    name: Run instrumented tests
    needs: [ktlint]
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
