name: Master branch CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleRemoteDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/remote/debug/app-remote-debug.apk